version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - wpnet

  wordpress:
    image: wordpress:latest
    container_name: wp_site
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpnet

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ab_tester
    networks:
      - wpnet
    stdin_open: true
    tty: true

networks:
  wpnet:
    external: true