version: '3.3'

services:
  php1:
    image: php:7.4-apache
    container_name: php_node1
    volumes:
      - ./index.php:/var/www/html/index.php
    command: >
      bash -c "echo 'ServerName localhost' > /etc/apache2/conf-available/fixname.conf &&
              a2enconf fixname &&
              apache2-foreground"
    networks:
      - balancenet

  php2:
    image: php:7.4-apache
    container_name: php_node2
    volumes:
      - ./index.php:/var/www/html/index.php
    command: >
      bash -c "echo 'ServerName localhost' > /etc/apache2/conf-available/fixname.conf &&
              a2enconf fixname &&
              apache2-foreground"
    networks:
      - balancenet

  php3:
    image: php:7.4-apache
    container_name: php_node3
    volumes:
      - ./index.php:/var/www/html/index.php
    command: >
      bash -c "echo 'ServerName localhost' > /etc/apache2/conf-available/fixname.conf &&
              a2enconf fixname &&
              apache2-foreground"
    networks:
      - balancenet

  nginx:
    image: nginx:latest
    container_name: nginx_balancer
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - balancenet
    depends_on:
      - php1
      - php2
      - php3


  tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ab_tester
    networks:
      - balancenet
    stdin_open: true
    tty: true

networks:
  balancenet:
